# -*- coding: utf-8 -*-
"""ReservoirSampling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xrl9D4GWH3tJe6iikuwowEFu6NGMaygV

## Importing the libraries
"""

import random
import sys

"""## Reservoir Sampling"""

def selectKItems(stream, size_of_stream, size_of_sample):
    i = 0
    reservoir = [0] * size_of_sample
    for i in range(size_of_sample):
        reservoir[i] = stream[i]

    while i < size_of_stream:
        j = random.randrange(i + 1)
        if j < size_of_sample:
            reservoir[j] = stream[i]
        i += 1

    print("Results from reservoir sampling algorithm:")
    printArray(reservoir, size_of_sample)

def printArray(stream, size_of_stream):
    for i in range(size_of_stream):
        print(stream[i], end=" ")
    print()

size_of_sample = 5
filename = "res.txt"
stream = open(filename, 'r')
streamArr = stream.readline().split(' ')
printArray(streamArr, len(streamArr))
size_of_stream = len(streamArr)
selectKItems(streamArr, size_of_stream, size_of_sample)

"""## Weighted Reservoir Sampling"""

def selectKItems(stream,W,weights, size_of_stream, size_of_sample):
    i = 0
    reservoir = [0] * size_of_sample
    for i in range(size_of_sample):
        reservoir[i] = stream[i]

    while i < size_of_stream:
        j = random.randrange(i + 1)
        w = weights[j]
        if w < size_of_sample:
            reservoir[j] = stream[i]
        i += 1

    print("Results from weighted reservoir sampling algorithm:")
    printArray(reservoir, size_of_sample)

size_of_sample = 10
filename = "res.txt"
stream = open(filename, 'r')
streamArr = stream.readline().split(' ')
size_of_stream = len(streamArr)
printArray(streamArr, len(streamArr))
weights = [0.5, 0.7, 0.4, 0.3, 0.2, 0.8, 0.1, 0.4, 0.5, 0.4, 0.9, 0.1]
W = 0
for i in range(len(weights)):
  W = W + weights[i]
selectKItems(streamArr, W, weights, size_of_stream, size_of_sample)